Adding qs3
Nexmo/stitch-ios-quickstart pull request #7
Opened 2018-03-29 01:09 UTC by ericgiannini

There are a few items to review : 

- UITableView's implementation for messages
- Socket.io bug fix 
- joining 
- typing indicator

2018-04-04 15:27 UTC, TheChrisVela requested changes

2018-04-04 15:27 UTC, TheChrisVela commented on docs/3-trying-it-out.md
> +If you're continuing on from the previous guide you may already have a `APP_JWT`. If not, generate a JWT using your Application ID (`YOUR_APP_ID`).
Don't need

2018-04-04 15:27 UTC, TheChrisVela commented on docs/3-trying-it-out.md
> +```bash
Don't need

2018-04-04 15:27 UTC, TheChrisVela commented on docs/3-trying-it-out.md
> +Let us added an instance of `UILabel` just below our instance of `UITableView` but above our instance of `TextField`. Later we will call it `typingIndicator` so that we show a message in the `typingI
"Let us" is used a lot in these last few sentences. Can we change it up a bit?

2018-04-04 15:27 UTC, TheChrisVela commented on docs/3-trying-it-out.md
> +...
Fix the indentation on this `...` please

2018-04-04 15:27 UTC, TheChrisVela commented on docs/3-trying-it-out.md
> +```Swift
Use lowercase `swift`. Please change for all code blocks

2018-04-04 15:27 UTC, TheChrisVela commented on docs/3-trying-it-out.md
> +...
Fix the indentation on this `...` please

2018-04-04 15:27 UTC, TheChrisVela commented on docs/3-trying-it-out.md
> +```Swift
Fix indentation please

2018-04-04 15:27 UTC, TheChrisVela commented on docs/3-trying-it-out.md
> +Designating `ChatViewController` as delegate for the UITableView means that the `ChatViewController` agrees to act on behalf of the `UITableView` to take care of whatever delegate methods are require
put UITableView in ``

2018-04-04 15:27 UTC, TheChrisVela commented on docs/3-trying-it-out.md
> +TODO REMOVE THIS paragraph:
What's up with this TODO?

2018-04-04 15:27 UTC, TheChrisVela commented on docs/3-trying-it-out.md
> +### 2.4 - Show a chat's history
Reword to "Show a conversation's history" or "Show chat history"?

2018-04-04 15:27 UTC, TheChrisVela commented on docs/3-trying-it-out.md
> +Our instnace of `tableView` ought to return as many rows now as there are events in our instance of `conversation`, whereas earlier it returned none. If it does, we are halfway there! The next step i
instnace typo instance

2018-04-04 15:27 UTC, TheChrisVela commented on docs/3-trying-it-out.md
> +// a set of unique members typing
Can we fix the indentation of the last 3 code blocks? They keep moving progressively to the right and then back to the left. Also the code comments are not on the same indentation as the methods.

2018-04-10 19:24 UTC, ericgiannini commented
@ChrisGuzman I updated following the review.

2018-04-18 15:33 UTC, TheChrisVela approved these changes
Let's merge it and get it on NDP!

2018-04-18 15:44 UTC, shams-ahmed commented
@ericgiannini next time can you do one commit for project and cocoapods update stuff than other commits for changes. github doesn't cope well with 1k+ loc changes

2018-04-18 15:53 UTC, ericgiannini commented
No problem! ;) Would you like me to exclude the Pod from Git tracking?

On Wed, Apr 18, 2018 at 8:44 AM, Shams Ahmed <notifications@github.com>
wrote:

> @ericgiannini <https://github.com/ericgiannini> next time can you do one
> commit for project and cocoapods update stuff than other commits for
> changes. github doesn't cope well with 1k+ loc changes
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Nexmo/conversation-ios-quickstart/pull/7#issuecomment-382433413>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMCHta92O2KVLSrzu31RZSzZF1-NoqJ3ks5tp19ogaJpZM4S_mEf>
> .
>

2018-04-20 21:18 UTC, merged